openapi: 3.0.0
info:
  title: Garibaldi API
  version: 1.0.0
  description: API for the El Gran Garibaldi restaurant

servers:
  - url: http://localhost:80/api
    description: Servidor local

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /register:
    post:
      tags:
        - Autenticación
      summary: Registrar un nuevo usuario
      requestBody:
        description: Datos del nuevo usuarioAPI para el restaurante el gran garibaldi
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Juan"
                email:
                  type: string
                  example: "juan@example.com"
                telefono:
                  type: string
                  example: "3123456789"
                contrasena:
                  type: string
                  example: "password123"
      responses:
        201:
          description: Usuario registrado con éxito
        400:
          description: Datos incompletos

  /login:
    post:
      tags:
        - Autenticación
      summary: Iniciar sesión
      requestBody:
        description: Datos de autenticación
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "juan@example.com"
                contrasena:
                  type: string
                  example: "password123"
      responses:
        200:
          description: Inicio de sesión exitoso
        401:
          description: Credenciales incorrectas

  /show-users:
    get:
      tags:
        - Usuarios
      summary: Obtener todos los usuarios (Solo administrador)
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de usuarios obtenida con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_usuario:
                      type: integer
                      example: 1
                    nombre:
                      type: string
                      example: "Juan"
                    email:
                      type: string
                      example: "juan@example.com"
                    telefono:
                      type: string
                      example: "3123456789"
                    contrasena_encriptada:
                      type: string
                      example: "$argon2id$v=19$m=65536,t=3,p=4$..."
                    rol:
                      type: string
                      example: "default"
        500:
          description: Error al obtener los usuarios

  /show-users/{id}:
    get:
      tags:
        - Usuarios
      summary: Obtener un usuario por ID (Solo administrador)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Detalles del usuario obtenidos con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_usuario:
                    type: integer
                    example: 1
                  nombre:
                    type: string
                    example: "Juan"
                  email:
                    type: string
                    example: "juan@example.com"
                  telefono:
                    type: string
                    example: "3123456789"
                  contrasena_encriptada:
                    type: string
                    example: "$argon2id$v=19$m=65536,t=3,p=4$..."
                  rol:
                    type: string
                    example: "default"
        404:
          description: Usuario no encontrado
        500:
          description: Error al obtener el usuario

  /create-user:
    post:
      tags:
        - Usuarios
      summary: Crear un nuevo usuario (Solo administrador)
      security:
        - bearerAuth: []
      requestBody:
        description: Datos para crear el nuevo usuario
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Juan"
                email:
                  type: string
                  example: "juan@example.com"
                telefono:
                  type: string
                  example: "3123456789"
                contrasena:
                  type: string
                  example: "password123"
                rol:
                  type: string
                  example: "default"
      responses:
        201:
          description: Usuario creado con éxito
        400:
          description: Datos incompletos
        500:
          description: Error al crear el usuario

  /delete-user/{id}:
    delete:
      tags:
        - Usuarios
      summary: Eliminar un usuario por ID (Solo administrador)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Usuario eliminado con éxito
        404:
          description: Usuario no encontrado
        500:
          description: Error al eliminar el usuario
  /comments:
    post:
      tags:
        - Comentarios
      summary: Crear un nuevo comentario 
      security:
        - bearerAuth: []
      requestBody:
        description: Datos del nuevo comentario
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  example: "Excelente servicio"
                calificacion:
                  type: integer
                  example: 5
                comentario:
                  type: string
                  example: "La comida fue fantástica y el servicio increíble."
      responses:
        201:
          description: Comentario creado con éxito
        400:
          description: Datos incompletos
        401:
          description: No autorizado, es necesario estar logueado

    get:
      tags:
        - Comentarios
      summary: Obtener todos los comentarios (Solo administrador), obtener los aprobados (Usuarios)
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de comentarios obtenida con éxito 
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_comentario:
                      type: integer
                      example: 1
                    id_usuario:
                      type: integer
                      example: 1
                    titulo:
                      type: string
                      example: "Excelente servicio"
                    calificacion:
                      type: integer
                      example: 5
                    comentario:
                      type: string
                      example: "La comida fue fantástica y el servicio increíble."
                    fecha_comentario:
                      type: string
                      example: "2024-10-05T12:34:56Z"
                    estado:
                      type: string
                      enum: ['Pendiente', 'Aprobado', 'Rechazado']
                      example: "Pendiente"
        401:
          description: No autorizado, es necesario estar logueado
        500:
          description: Error al obtener los comentarios

  /comments/{id_comentario}:
    patch:
      tags:
        - Comentarios
      summary: Cambiar el estado de un comentario (Solo administrador)
      security:
        - bearerAuth: []
      parameters:
        - name: id_comentario
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: Estado a modificar
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                estado:
                  type: string
                  enum: ['Pendiente', 'Aprobado', 'Rechazado']
                  example: "Aprobado"
      responses:
        200:
          description: Estado del comentario modificado con éxito
        400:
          description: Datos incompletos o incorrectos
        401:
          description: No autorizado, solo administradores pueden modificar el estado
        404:
          description: Comentario no encontrado
        500:
          description: Error al modificar el estado del comentario
